### ISSUE TITLE
Used TIMEDOUT/TIMEOUT instead of FAILED

### ISSUE THREAD

**Issue by mayur-raja** [IBM/operator-collection-sdk#42]
#### Describe the problem you need a feature to resolve.

When creating an operator collection, we issue messages like: 

TASK [Create OperatorCollection] *******************************************************************************************************************************
changed: [localhost]
FAILED - RETRYING: [localhost]: Validate OperatorCollection installed successfully (5 retries left).

TASK [Validate OperatorCollection installed successfully] *******************************************************************************************************************************
ok: [localhost]

TASK [Create SSH Credential Secret with passphrase] *******************************************************************************************************************************
changed: [localhost]

TASK [Create SubOperatorConfig with mapped credential] *******************************************************************************************************************************
changed: [localhost]
FAILED - RETRYING: [localhost]: Validate SubOperatorConfig installed successfully (30 retries left).
FAILED - RETRYING: [localhost]: Validate SubOperatorConfig installed successfully (29 retries left).
....

End users find it alarming when they see the word FAILED. 

#### Describe the solution you'd like.

For cases where there is a genuine timeout, can we replace the word FAILED with TIMEDOUT or TIMEOUT ? 
If we fail to validate after all retry attempts have been exhaused, then we can say FAILED.

The other thing to consider is to increase the time interval between validation checks and hence reduce the frequency of issuing such messages. 

Thank you.

**Comment by freemanlatrell** [comment]
@mayur-raja Unfortunately we don't have any control over the `FAILED` error message, as this is generated by Ansible when polling. As for increasing the intervals....this could also be an issue for deployments that install fairly quickly....but are delayed because we have such a long polling period that takes a while before performing another check. So there are pros and cons to each approach.

I'm going close this one, but please re-open if needed.

**Comment by mayur-raja** [comment]
Thanks Latrell, I understand.
