### ISSUE TITLE
Typo in ocsdk-create-operator output message

### ISSUE THREAD

**Issue by farrart** [IBM/operator-collection-sdk#8]
#### What did you do?

When running the ocsdk-create-operator command I see a typo in one of the message prompts

#### What did you expect to see?

The typo should be corrected

#### What did you see instead? Under which circumstances?

The message reads:
`Enter you SSH Username for this endpoint (Press Enter to skip if the zoscb-encrypt CLI isn't installed):
`
#### Collection Version

`$ ansible-galaxy collection verify ibm.operator_collection_sdk`

ibm.operator_collection_sdk:0.2.0

#### Additional context

![image](https://github.com/IBM/operator-collection-sdk/assets/38953320/01276e51-5e5f-427a-8fa0-2e059599ec3f)

**Comment by freemanlatrell** [comment]
Fixed. Closing
