### ISSUE TITLE
Change z/OC to z/OS

### ISSUE THREAD

**Issue by mayur-raja** [IBM/operator-collection-sdk#9]
### What is the link to the document from the "main" branch?

/ibm/operator_collection_development/README.md

### Which section(s) is the issue in?

Prerequisites

### What needs fixing?

Link 'z/OC Cloud Broker Encryption CLI' should read 'z/OS Cloud Broker Encryption CLI'

**Comment by freemanlatrell** [comment]
Fixed in commit https://github.com/IBM/operator-collection-sdk/commit/d66875ff427752943d61ec14eb154f0298c30f38
